// This file is generated by the effect-codex-app-server package. Do not edit manually.
// Upstream protocol ref: be75785504ff152fa6333e380a2d50642f42fba0

import * as CodexSchema from "./schema.gen.ts";

export const CLIENT_REQUEST_METHODS = {
  initialize: "initialize",
  "thread/start": "thread/start",
  "thread/resume": "thread/resume",
  "thread/fork": "thread/fork",
  "thread/archive": "thread/archive",
  "thread/unsubscribe": "thread/unsubscribe",
  "thread/name/set": "thread/name/set",
  "thread/metadata/update": "thread/metadata/update",
  "thread/unarchive": "thread/unarchive",
  "thread/compact/start": "thread/compact/start",
  "thread/shellCommand": "thread/shellCommand",
  "thread/rollback": "thread/rollback",
  "thread/list": "thread/list",
  "thread/loaded/list": "thread/loaded/list",
  "thread/read": "thread/read",
  "thread/turns/list": "thread/turns/list",
  "thread/inject_items": "thread/inject_items",
  "skills/list": "skills/list",
  "marketplace/add": "marketplace/add",
  "marketplace/remove": "marketplace/remove",
  "plugin/list": "plugin/list",
  "plugin/read": "plugin/read",
  "app/list": "app/list",
  "device/key/create": "device/key/create",
  "device/key/public": "device/key/public",
  "device/key/sign": "device/key/sign",
  "fs/readFile": "fs/readFile",
  "fs/writeFile": "fs/writeFile",
  "fs/createDirectory": "fs/createDirectory",
  "fs/getMetadata": "fs/getMetadata",
  "fs/readDirectory": "fs/readDirectory",
  "fs/remove": "fs/remove",
  "fs/copy": "fs/copy",
  "fs/watch": "fs/watch",
  "fs/unwatch": "fs/unwatch",
  "skills/config/write": "skills/config/write",
  "plugin/install": "plugin/install",
  "plugin/uninstall": "plugin/uninstall",
  "turn/start": "turn/start",
  "turn/steer": "turn/steer",
  "turn/interrupt": "turn/interrupt",
  "review/start": "review/start",
  "model/list": "model/list",
  "experimentalFeature/list": "experimentalFeature/list",
  "experimentalFeature/enablement/set": "experimentalFeature/enablement/set",
  "mcpServer/oauth/login": "mcpServer/oauth/login",
  "config/mcpServer/reload": "config/mcpServer/reload",
  "mcpServerStatus/list": "mcpServerStatus/list",
  "mcpServer/resource/read": "mcpServer/resource/read",
  "mcpServer/tool/call": "mcpServer/tool/call",
  "windowsSandbox/setupStart": "windowsSandbox/setupStart",
  "account/login/start": "account/login/start",
  "account/login/cancel": "account/login/cancel",
  "account/logout": "account/logout",
  "account/rateLimits/read": "account/rateLimits/read",
  "account/sendAddCreditsNudgeEmail": "account/sendAddCreditsNudgeEmail",
  "feedback/upload": "feedback/upload",
  "command/exec": "command/exec",
  "command/exec/write": "command/exec/write",
  "command/exec/terminate": "command/exec/terminate",
  "command/exec/resize": "command/exec/resize",
  "config/read": "config/read",
  "externalAgentConfig/detect": "externalAgentConfig/detect",
  "externalAgentConfig/import": "externalAgentConfig/import",
  "config/value/write": "config/value/write",
  "config/batchWrite": "config/batchWrite",
  "configRequirements/read": "configRequirements/read",
  "account/read": "account/read",
  getConversationSummary: "getConversationSummary",
  gitDiffToRemote: "gitDiffToRemote",
  getAuthStatus: "getAuthStatus",
  fuzzyFileSearch: "fuzzyFileSearch",
} as const;

export const CLIENT_NOTIFICATION_METHODS = {
  initialized: "initialized",
} as const;

export const SERVER_REQUEST_METHODS = {
  "item/commandExecution/requestApproval": "item/commandExecution/requestApproval",
  "item/fileChange/requestApproval": "item/fileChange/requestApproval",
  "item/tool/requestUserInput": "item/tool/requestUserInput",
  "mcpServer/elicitation/request": "mcpServer/elicitation/request",
  "item/permissions/requestApproval": "item/permissions/requestApproval",
  "item/tool/call": "item/tool/call",
  "account/chatgptAuthTokens/refresh": "account/chatgptAuthTokens/refresh",
  applyPatchApproval: "applyPatchApproval",
  execCommandApproval: "execCommandApproval",
} as const;

export const SERVER_NOTIFICATION_METHODS = {
  error: "error",
  "thread/started": "thread/started",
  "thread/status/changed": "thread/status/changed",
  "thread/archived": "thread/archived",
  "thread/unarchived": "thread/unarchived",
  "thread/closed": "thread/closed",
  "skills/changed": "skills/changed",
  "thread/name/updated": "thread/name/updated",
  "thread/tokenUsage/updated": "thread/tokenUsage/updated",
  "turn/started": "turn/started",
  "hook/started": "hook/started",
  "turn/completed": "turn/completed",
  "hook/completed": "hook/completed",
  "turn/diff/updated": "turn/diff/updated",
  "turn/plan/updated": "turn/plan/updated",
  "item/started": "item/started",
  "item/autoApprovalReview/started": "item/autoApprovalReview/started",
  "item/autoApprovalReview/completed": "item/autoApprovalReview/completed",
  "item/completed": "item/completed",
  "rawResponseItem/completed": "rawResponseItem/completed",
  "item/agentMessage/delta": "item/agentMessage/delta",
  "item/plan/delta": "item/plan/delta",
  "command/exec/outputDelta": "command/exec/outputDelta",
  "item/commandExecution/outputDelta": "item/commandExecution/outputDelta",
  "item/commandExecution/terminalInteraction": "item/commandExecution/terminalInteraction",
  "item/fileChange/outputDelta": "item/fileChange/outputDelta",
  "item/fileChange/patchUpdated": "item/fileChange/patchUpdated",
  "serverRequest/resolved": "serverRequest/resolved",
  "item/mcpToolCall/progress": "item/mcpToolCall/progress",
  "mcpServer/oauthLogin/completed": "mcpServer/oauthLogin/completed",
  "mcpServer/startupStatus/updated": "mcpServer/startupStatus/updated",
  "account/updated": "account/updated",
  "account/rateLimits/updated": "account/rateLimits/updated",
  "app/list/updated": "app/list/updated",
  "externalAgentConfig/import/completed": "externalAgentConfig/import/completed",
  "fs/changed": "fs/changed",
  "item/reasoning/summaryTextDelta": "item/reasoning/summaryTextDelta",
  "item/reasoning/summaryPartAdded": "item/reasoning/summaryPartAdded",
  "item/reasoning/textDelta": "item/reasoning/textDelta",
  "thread/compacted": "thread/compacted",
  "model/rerouted": "model/rerouted",
  warning: "warning",
  deprecationNotice: "deprecationNotice",
  configWarning: "configWarning",
  "fuzzyFileSearch/sessionUpdated": "fuzzyFileSearch/sessionUpdated",
  "fuzzyFileSearch/sessionCompleted": "fuzzyFileSearch/sessionCompleted",
  "thread/realtime/started": "thread/realtime/started",
  "thread/realtime/itemAdded": "thread/realtime/itemAdded",
  "thread/realtime/transcript/delta": "thread/realtime/transcript/delta",
  "thread/realtime/transcript/done": "thread/realtime/transcript/done",
  "thread/realtime/outputAudio/delta": "thread/realtime/outputAudio/delta",
  "thread/realtime/sdp": "thread/realtime/sdp",
  "thread/realtime/error": "thread/realtime/error",
  "thread/realtime/closed": "thread/realtime/closed",
  "windows/worldWritableWarning": "windows/worldWritableWarning",
  "windowsSandbox/setupCompleted": "windowsSandbox/setupCompleted",
  "account/login/completed": "account/login/completed",
} as const;

export type ClientRequestMethod = keyof typeof CLIENT_REQUEST_METHODS;
export type ClientNotificationMethod = keyof typeof CLIENT_NOTIFICATION_METHODS;
export type ServerRequestMethod = keyof typeof SERVER_REQUEST_METHODS;
export type ServerNotificationMethod = keyof typeof SERVER_NOTIFICATION_METHODS;

export interface ClientRequestParamsByMethod {
  readonly initialize: typeof CodexSchema.V1InitializeParams.Type;
  readonly "thread/start": typeof CodexSchema.V2ThreadStartParams.Type;
  readonly "thread/resume": typeof CodexSchema.V2ThreadResumeParams.Type;
  readonly "thread/fork": typeof CodexSchema.V2ThreadForkParams.Type;
  readonly "thread/archive": typeof CodexSchema.V2ThreadArchiveParams.Type;
  readonly "thread/unsubscribe": typeof CodexSchema.V2ThreadUnsubscribeParams.Type;
  readonly "thread/name/set": typeof CodexSchema.V2ThreadSetNameParams.Type;
  readonly "thread/metadata/update": typeof CodexSchema.V2ThreadMetadataUpdateParams.Type;
  readonly "thread/unarchive": typeof CodexSchema.V2ThreadUnarchiveParams.Type;
  readonly "thread/compact/start": typeof CodexSchema.V2ThreadCompactStartParams.Type;
  readonly "thread/shellCommand": typeof CodexSchema.V2ThreadShellCommandParams.Type;
  readonly "thread/rollback": typeof CodexSchema.V2ThreadRollbackParams.Type;
  readonly "thread/list": typeof CodexSchema.V2ThreadListParams.Type;
  readonly "thread/loaded/list": typeof CodexSchema.V2ThreadLoadedListParams.Type;
  readonly "thread/read": typeof CodexSchema.V2ThreadReadParams.Type;
  readonly "thread/turns/list": typeof CodexSchema.V2ThreadTurnsListParams.Type;
  readonly "thread/inject_items": typeof CodexSchema.V2ThreadInjectItemsParams.Type;
  readonly "skills/list": typeof CodexSchema.V2SkillsListParams.Type;
  readonly "marketplace/add": typeof CodexSchema.V2MarketplaceAddParams.Type;
  readonly "marketplace/remove": typeof CodexSchema.V2MarketplaceRemoveParams.Type;
  readonly "plugin/list": typeof CodexSchema.V2PluginListParams.Type;
  readonly "plugin/read": typeof CodexSchema.V2PluginReadParams.Type;
  readonly "app/list": typeof CodexSchema.V2AppsListParams.Type;
  readonly "device/key/create": typeof CodexSchema.V2DeviceKeyCreateParams.Type;
  readonly "device/key/public": typeof CodexSchema.V2DeviceKeyPublicParams.Type;
  readonly "device/key/sign": typeof CodexSchema.V2DeviceKeySignParams.Type;
  readonly "fs/readFile": typeof CodexSchema.V2FsReadFileParams.Type;
  readonly "fs/writeFile": typeof CodexSchema.V2FsWriteFileParams.Type;
  readonly "fs/createDirectory": typeof CodexSchema.V2FsCreateDirectoryParams.Type;
  readonly "fs/getMetadata": typeof CodexSchema.V2FsGetMetadataParams.Type;
  readonly "fs/readDirectory": typeof CodexSchema.V2FsReadDirectoryParams.Type;
  readonly "fs/remove": typeof CodexSchema.V2FsRemoveParams.Type;
  readonly "fs/copy": typeof CodexSchema.V2FsCopyParams.Type;
  readonly "fs/watch": typeof CodexSchema.V2FsWatchParams.Type;
  readonly "fs/unwatch": typeof CodexSchema.V2FsUnwatchParams.Type;
  readonly "skills/config/write": typeof CodexSchema.V2SkillsConfigWriteParams.Type;
  readonly "plugin/install": typeof CodexSchema.V2PluginInstallParams.Type;
  readonly "plugin/uninstall": typeof CodexSchema.V2PluginUninstallParams.Type;
  readonly "turn/start": typeof CodexSchema.V2TurnStartParams.Type;
  readonly "turn/steer": typeof CodexSchema.V2TurnSteerParams.Type;
  readonly "turn/interrupt": typeof CodexSchema.V2TurnInterruptParams.Type;
  readonly "review/start": typeof CodexSchema.V2ReviewStartParams.Type;
  readonly "model/list": typeof CodexSchema.V2ModelListParams.Type;
  readonly "experimentalFeature/list": typeof CodexSchema.V2ExperimentalFeatureListParams.Type;
  readonly "experimentalFeature/enablement/set": typeof CodexSchema.V2ExperimentalFeatureEnablementSetParams.Type;
  readonly "mcpServer/oauth/login": typeof CodexSchema.V2McpServerOauthLoginParams.Type;
  readonly "config/mcpServer/reload": undefined;
  readonly "mcpServerStatus/list": typeof CodexSchema.V2ListMcpServerStatusParams.Type;
  readonly "mcpServer/resource/read": typeof CodexSchema.V2McpResourceReadParams.Type;
  readonly "mcpServer/tool/call": typeof CodexSchema.V2McpServerToolCallParams.Type;
  readonly "windowsSandbox/setupStart": typeof CodexSchema.V2WindowsSandboxSetupStartParams.Type;
  readonly "account/login/start": typeof CodexSchema.V2LoginAccountParams.Type;
  readonly "account/login/cancel": typeof CodexSchema.V2CancelLoginAccountParams.Type;
  readonly "account/logout": undefined;
  readonly "account/rateLimits/read": undefined;
  readonly "account/sendAddCreditsNudgeEmail": typeof CodexSchema.V2SendAddCreditsNudgeEmailParams.Type;
  readonly "feedback/upload": typeof CodexSchema.V2FeedbackUploadParams.Type;
  readonly "command/exec": typeof CodexSchema.V2CommandExecParams.Type;
  readonly "command/exec/write": typeof CodexSchema.V2CommandExecWriteParams.Type;
  readonly "command/exec/terminate": typeof CodexSchema.V2CommandExecTerminateParams.Type;
  readonly "command/exec/resize": typeof CodexSchema.V2CommandExecResizeParams.Type;
  readonly "config/read": typeof CodexSchema.V2ConfigReadParams.Type;
  readonly "externalAgentConfig/detect": typeof CodexSchema.V2ExternalAgentConfigDetectParams.Type;
  readonly "externalAgentConfig/import": typeof CodexSchema.V2ExternalAgentConfigImportParams.Type;
  readonly "config/value/write": typeof CodexSchema.V2ConfigValueWriteParams.Type;
  readonly "config/batchWrite": typeof CodexSchema.V2ConfigBatchWriteParams.Type;
  readonly "configRequirements/read": undefined;
  readonly "account/read": typeof CodexSchema.V2GetAccountParams.Type;
  readonly getConversationSummary: typeof CodexSchema.GetConversationSummaryParams.Type;
  readonly gitDiffToRemote: typeof CodexSchema.GitDiffToRemoteParams.Type;
  readonly getAuthStatus: typeof CodexSchema.GetAuthStatusParams.Type;
  readonly fuzzyFileSearch: typeof CodexSchema.FuzzyFileSearchParams.Type;
}

export interface ClientRequestResponsesByMethod {
  readonly initialize: typeof CodexSchema.V1InitializeResponse.Type;
  readonly "thread/start": typeof CodexSchema.V2ThreadStartResponse.Type;
  readonly "thread/resume": typeof CodexSchema.V2ThreadResumeResponse.Type;
  readonly "thread/fork": typeof CodexSchema.V2ThreadForkResponse.Type;
  readonly "thread/archive": typeof CodexSchema.V2ThreadArchiveResponse.Type;
  readonly "thread/unsubscribe": typeof CodexSchema.V2ThreadUnsubscribeResponse.Type;
  readonly "thread/name/set": typeof CodexSchema.V2ThreadSetNameResponse.Type;
  readonly "thread/metadata/update": typeof CodexSchema.V2ThreadMetadataUpdateResponse.Type;
  readonly "thread/unarchive": typeof CodexSchema.V2ThreadUnarchiveResponse.Type;
  readonly "thread/compact/start": typeof CodexSchema.V2ThreadCompactStartResponse.Type;
  readonly "thread/shellCommand": typeof CodexSchema.V2ThreadShellCommandResponse.Type;
  readonly "thread/rollback": typeof CodexSchema.V2ThreadRollbackResponse.Type;
  readonly "thread/list": typeof CodexSchema.V2ThreadListResponse.Type;
  readonly "thread/loaded/list": typeof CodexSchema.V2ThreadLoadedListResponse.Type;
  readonly "thread/read": typeof CodexSchema.V2ThreadReadResponse.Type;
  readonly "thread/turns/list": typeof CodexSchema.V2ThreadTurnsListResponse.Type;
  readonly "thread/inject_items": typeof CodexSchema.V2ThreadInjectItemsResponse.Type;
  readonly "skills/list": typeof CodexSchema.V2SkillsListResponse.Type;
  readonly "marketplace/add": typeof CodexSchema.V2MarketplaceAddResponse.Type;
  readonly "marketplace/remove": typeof CodexSchema.V2MarketplaceRemoveResponse.Type;
  readonly "plugin/list": typeof CodexSchema.V2PluginListResponse.Type;
  readonly "plugin/read": typeof CodexSchema.V2PluginReadResponse.Type;
  readonly "app/list": typeof CodexSchema.V2AppsListResponse.Type;
  readonly "device/key/create": typeof CodexSchema.V2DeviceKeyCreateResponse.Type;
  readonly "device/key/public": typeof CodexSchema.V2DeviceKeyPublicResponse.Type;
  readonly "device/key/sign": typeof CodexSchema.V2DeviceKeySignResponse.Type;
  readonly "fs/readFile": typeof CodexSchema.V2FsReadFileResponse.Type;
  readonly "fs/writeFile": typeof CodexSchema.V2FsWriteFileResponse.Type;
  readonly "fs/createDirectory": typeof CodexSchema.V2FsCreateDirectoryResponse.Type;
  readonly "fs/getMetadata": typeof CodexSchema.V2FsGetMetadataResponse.Type;
  readonly "fs/readDirectory": typeof CodexSchema.V2FsReadDirectoryResponse.Type;
  readonly "fs/remove": typeof CodexSchema.V2FsRemoveResponse.Type;
  readonly "fs/copy": typeof CodexSchema.V2FsCopyResponse.Type;
  readonly "fs/watch": typeof CodexSchema.V2FsWatchResponse.Type;
  readonly "fs/unwatch": typeof CodexSchema.V2FsUnwatchResponse.Type;
  readonly "skills/config/write": typeof CodexSchema.V2SkillsConfigWriteResponse.Type;
  readonly "plugin/install": typeof CodexSchema.V2PluginInstallResponse.Type;
  readonly "plugin/uninstall": typeof CodexSchema.V2PluginUninstallResponse.Type;
  readonly "turn/start": typeof CodexSchema.V2TurnStartResponse.Type;
  readonly "turn/steer": typeof CodexSchema.V2TurnSteerResponse.Type;
  readonly "turn/interrupt": typeof CodexSchema.V2TurnInterruptResponse.Type;
  readonly "review/start": typeof CodexSchema.V2ReviewStartResponse.Type;
  readonly "model/list": typeof CodexSchema.V2ModelListResponse.Type;
  readonly "experimentalFeature/list": typeof CodexSchema.V2ExperimentalFeatureListResponse.Type;
  readonly "experimentalFeature/enablement/set": typeof CodexSchema.V2ExperimentalFeatureEnablementSetResponse.Type;
  readonly "mcpServer/oauth/login": typeof CodexSchema.V2McpServerOauthLoginResponse.Type;
  readonly "config/mcpServer/reload": typeof CodexSchema.V2McpServerRefreshResponse.Type;
  readonly "mcpServerStatus/list": typeof CodexSchema.V2ListMcpServerStatusResponse.Type;
  readonly "mcpServer/resource/read": typeof CodexSchema.V2McpResourceReadResponse.Type;
  readonly "mcpServer/tool/call": typeof CodexSchema.V2McpServerToolCallResponse.Type;
  readonly "windowsSandbox/setupStart": typeof CodexSchema.V2WindowsSandboxSetupStartResponse.Type;
  readonly "account/login/start": typeof CodexSchema.V2LoginAccountResponse.Type;
  readonly "account/login/cancel": typeof CodexSchema.V2CancelLoginAccountResponse.Type;
  readonly "account/logout": typeof CodexSchema.V2LogoutAccountResponse.Type;
  readonly "account/rateLimits/read": typeof CodexSchema.V2GetAccountRateLimitsResponse.Type;
  readonly "account/sendAddCreditsNudgeEmail": typeof CodexSchema.V2SendAddCreditsNudgeEmailResponse.Type;
  readonly "feedback/upload": typeof CodexSchema.V2FeedbackUploadResponse.Type;
  readonly "command/exec": typeof CodexSchema.V2CommandExecResponse.Type;
  readonly "command/exec/write": typeof CodexSchema.V2CommandExecWriteResponse.Type;
  readonly "command/exec/terminate": typeof CodexSchema.V2CommandExecTerminateResponse.Type;
  readonly "command/exec/resize": typeof CodexSchema.V2CommandExecResizeResponse.Type;
  readonly "config/read": typeof CodexSchema.V2ConfigReadResponse.Type;
  readonly "externalAgentConfig/detect": typeof CodexSchema.V2ExternalAgentConfigDetectResponse.Type;
  readonly "externalAgentConfig/import": typeof CodexSchema.V2ExternalAgentConfigImportResponse.Type;
  readonly "config/value/write": typeof CodexSchema.V2ConfigWriteResponse.Type;
  readonly "config/batchWrite": typeof CodexSchema.V2ConfigWriteResponse.Type;
  readonly "configRequirements/read": typeof CodexSchema.V2ConfigRequirementsReadResponse.Type;
  readonly "account/read": typeof CodexSchema.V2GetAccountResponse.Type;
  readonly getConversationSummary: typeof CodexSchema.GetConversationSummaryResponse.Type;
  readonly gitDiffToRemote: typeof CodexSchema.GitDiffToRemoteResponse.Type;
  readonly getAuthStatus: typeof CodexSchema.GetAuthStatusResponse.Type;
  readonly fuzzyFileSearch: typeof CodexSchema.FuzzyFileSearchResponse.Type;
}

export interface ClientNotificationParamsByMethod {
  readonly initialized: undefined;
}

export interface ServerRequestParamsByMethod {
  readonly "item/commandExecution/requestApproval": typeof CodexSchema.CommandExecutionRequestApprovalParams.Type;
  readonly "item/fileChange/requestApproval": typeof CodexSchema.FileChangeRequestApprovalParams.Type;
  readonly "item/tool/requestUserInput": typeof CodexSchema.ToolRequestUserInputParams.Type;
  readonly "mcpServer/elicitation/request": typeof CodexSchema.McpServerElicitationRequestParams.Type;
  readonly "item/permissions/requestApproval": typeof CodexSchema.PermissionsRequestApprovalParams.Type;
  readonly "item/tool/call": typeof CodexSchema.DynamicToolCallParams.Type;
  readonly "account/chatgptAuthTokens/refresh": typeof CodexSchema.ChatgptAuthTokensRefreshParams.Type;
  readonly applyPatchApproval: typeof CodexSchema.ApplyPatchApprovalParams.Type;
  readonly execCommandApproval: typeof CodexSchema.ExecCommandApprovalParams.Type;
}

export interface ServerRequestResponsesByMethod {
  readonly "item/commandExecution/requestApproval": typeof CodexSchema.CommandExecutionRequestApprovalResponse.Type;
  readonly "item/fileChange/requestApproval": typeof CodexSchema.FileChangeRequestApprovalResponse.Type;
  readonly "item/tool/requestUserInput": typeof CodexSchema.ToolRequestUserInputResponse.Type;
  readonly "mcpServer/elicitation/request": typeof CodexSchema.McpServerElicitationRequestResponse.Type;
  readonly "item/permissions/requestApproval": typeof CodexSchema.PermissionsRequestApprovalResponse.Type;
  readonly "item/tool/call": typeof CodexSchema.DynamicToolCallResponse.Type;
  readonly "account/chatgptAuthTokens/refresh": typeof CodexSchema.ChatgptAuthTokensRefreshResponse.Type;
  readonly applyPatchApproval: typeof CodexSchema.ApplyPatchApprovalResponse.Type;
  readonly execCommandApproval: typeof CodexSchema.ExecCommandApprovalResponse.Type;
}

export interface ServerNotificationParamsByMethod {
  readonly error: typeof CodexSchema.V2ErrorNotification.Type;
  readonly "thread/started": typeof CodexSchema.V2ThreadStartedNotification.Type;
  readonly "thread/status/changed": typeof CodexSchema.V2ThreadStatusChangedNotification.Type;
  readonly "thread/archived": typeof CodexSchema.V2ThreadArchivedNotification.Type;
  readonly "thread/unarchived": typeof CodexSchema.V2ThreadUnarchivedNotification.Type;
  readonly "thread/closed": typeof CodexSchema.V2ThreadClosedNotification.Type;
  readonly "skills/changed": typeof CodexSchema.V2SkillsChangedNotification.Type;
  readonly "thread/name/updated": typeof CodexSchema.V2ThreadNameUpdatedNotification.Type;
  readonly "thread/tokenUsage/updated": typeof CodexSchema.V2ThreadTokenUsageUpdatedNotification.Type;
  readonly "turn/started": typeof CodexSchema.V2TurnStartedNotification.Type;
  readonly "hook/started": typeof CodexSchema.V2HookStartedNotification.Type;
  readonly "turn/completed": typeof CodexSchema.V2TurnCompletedNotification.Type;
  readonly "hook/completed": typeof CodexSchema.V2HookCompletedNotification.Type;
  readonly "turn/diff/updated": typeof CodexSchema.V2TurnDiffUpdatedNotification.Type;
  readonly "turn/plan/updated": typeof CodexSchema.V2TurnPlanUpdatedNotification.Type;
  readonly "item/started": typeof CodexSchema.V2ItemStartedNotification.Type;
  readonly "item/autoApprovalReview/started": typeof CodexSchema.V2ItemGuardianApprovalReviewStartedNotification.Type;
  readonly "item/autoApprovalReview/completed": typeof CodexSchema.V2ItemGuardianApprovalReviewCompletedNotification.Type;
  readonly "item/completed": typeof CodexSchema.V2ItemCompletedNotification.Type;
  readonly "rawResponseItem/completed": typeof CodexSchema.V2RawResponseItemCompletedNotification.Type;
  readonly "item/agentMessage/delta": typeof CodexSchema.V2AgentMessageDeltaNotification.Type;
  readonly "item/plan/delta": typeof CodexSchema.V2PlanDeltaNotification.Type;
  readonly "command/exec/outputDelta": typeof CodexSchema.V2CommandExecOutputDeltaNotification.Type;
  readonly "item/commandExecution/outputDelta": typeof CodexSchema.V2CommandExecutionOutputDeltaNotification.Type;
  readonly "item/commandExecution/terminalInteraction": typeof CodexSchema.V2TerminalInteractionNotification.Type;
  readonly "item/fileChange/outputDelta": typeof CodexSchema.V2FileChangeOutputDeltaNotification.Type;
  readonly "item/fileChange/patchUpdated": typeof CodexSchema.V2FileChangePatchUpdatedNotification.Type;
  readonly "serverRequest/resolved": typeof CodexSchema.V2ServerRequestResolvedNotification.Type;
  readonly "item/mcpToolCall/progress": typeof CodexSchema.V2McpToolCallProgressNotification.Type;
  readonly "mcpServer/oauthLogin/completed": typeof CodexSchema.V2McpServerOauthLoginCompletedNotification.Type;
  readonly "mcpServer/startupStatus/updated": typeof CodexSchema.V2McpServerStatusUpdatedNotification.Type;
  readonly "account/updated": typeof CodexSchema.V2AccountUpdatedNotification.Type;
  readonly "account/rateLimits/updated": typeof CodexSchema.V2AccountRateLimitsUpdatedNotification.Type;
  readonly "app/list/updated": typeof CodexSchema.V2AppListUpdatedNotification.Type;
  readonly "externalAgentConfig/import/completed": typeof CodexSchema.V2ExternalAgentConfigImportCompletedNotification.Type;
  readonly "fs/changed": typeof CodexSchema.V2FsChangedNotification.Type;
  readonly "item/reasoning/summaryTextDelta": typeof CodexSchema.V2ReasoningSummaryTextDeltaNotification.Type;
  readonly "item/reasoning/summaryPartAdded": typeof CodexSchema.V2ReasoningSummaryPartAddedNotification.Type;
  readonly "item/reasoning/textDelta": typeof CodexSchema.V2ReasoningTextDeltaNotification.Type;
  readonly "thread/compacted": typeof CodexSchema.V2ContextCompactedNotification.Type;
  readonly "model/rerouted": typeof CodexSchema.V2ModelReroutedNotification.Type;
  readonly warning: typeof CodexSchema.V2WarningNotification.Type;
  readonly deprecationNotice: typeof CodexSchema.V2DeprecationNoticeNotification.Type;
  readonly configWarning: typeof CodexSchema.V2ConfigWarningNotification.Type;
  readonly "fuzzyFileSearch/sessionUpdated": typeof CodexSchema.FuzzyFileSearchSessionUpdatedNotification.Type;
  readonly "fuzzyFileSearch/sessionCompleted": typeof CodexSchema.FuzzyFileSearchSessionCompletedNotification.Type;
  readonly "thread/realtime/started": typeof CodexSchema.V2ThreadRealtimeStartedNotification.Type;
  readonly "thread/realtime/itemAdded": typeof CodexSchema.V2ThreadRealtimeItemAddedNotification.Type;
  readonly "thread/realtime/transcript/delta": typeof CodexSchema.V2ThreadRealtimeTranscriptDeltaNotification.Type;
  readonly "thread/realtime/transcript/done": typeof CodexSchema.V2ThreadRealtimeTranscriptDoneNotification.Type;
  readonly "thread/realtime/outputAudio/delta": typeof CodexSchema.V2ThreadRealtimeOutputAudioDeltaNotification.Type;
  readonly "thread/realtime/sdp": typeof CodexSchema.V2ThreadRealtimeSdpNotification.Type;
  readonly "thread/realtime/error": typeof CodexSchema.V2ThreadRealtimeErrorNotification.Type;
  readonly "thread/realtime/closed": typeof CodexSchema.V2ThreadRealtimeClosedNotification.Type;
  readonly "windows/worldWritableWarning": typeof CodexSchema.V2WindowsWorldWritableWarningNotification.Type;
  readonly "windowsSandbox/setupCompleted": typeof CodexSchema.V2WindowsSandboxSetupCompletedNotification.Type;
  readonly "account/login/completed": typeof CodexSchema.V2AccountLoginCompletedNotification.Type;
}

export const CLIENT_REQUEST_PARAMS = {
  initialize: CodexSchema.V1InitializeParams,
  "thread/start": CodexSchema.V2ThreadStartParams,
  "thread/resume": CodexSchema.V2ThreadResumeParams,
  "thread/fork": CodexSchema.V2ThreadForkParams,
  "thread/archive": CodexSchema.V2ThreadArchiveParams,
  "thread/unsubscribe": CodexSchema.V2ThreadUnsubscribeParams,
  "thread/name/set": CodexSchema.V2ThreadSetNameParams,
  "thread/metadata/update": CodexSchema.V2ThreadMetadataUpdateParams,
  "thread/unarchive": CodexSchema.V2ThreadUnarchiveParams,
  "thread/compact/start": CodexSchema.V2ThreadCompactStartParams,
  "thread/shellCommand": CodexSchema.V2ThreadShellCommandParams,
  "thread/rollback": CodexSchema.V2ThreadRollbackParams,
  "thread/list": CodexSchema.V2ThreadListParams,
  "thread/loaded/list": CodexSchema.V2ThreadLoadedListParams,
  "thread/read": CodexSchema.V2ThreadReadParams,
  "thread/turns/list": CodexSchema.V2ThreadTurnsListParams,
  "thread/inject_items": CodexSchema.V2ThreadInjectItemsParams,
  "skills/list": CodexSchema.V2SkillsListParams,
  "marketplace/add": CodexSchema.V2MarketplaceAddParams,
  "marketplace/remove": CodexSchema.V2MarketplaceRemoveParams,
  "plugin/list": CodexSchema.V2PluginListParams,
  "plugin/read": CodexSchema.V2PluginReadParams,
  "app/list": CodexSchema.V2AppsListParams,
  "device/key/create": CodexSchema.V2DeviceKeyCreateParams,
  "device/key/public": CodexSchema.V2DeviceKeyPublicParams,
  "device/key/sign": CodexSchema.V2DeviceKeySignParams,
  "fs/readFile": CodexSchema.V2FsReadFileParams,
  "fs/writeFile": CodexSchema.V2FsWriteFileParams,
  "fs/createDirectory": CodexSchema.V2FsCreateDirectoryParams,
  "fs/getMetadata": CodexSchema.V2FsGetMetadataParams,
  "fs/readDirectory": CodexSchema.V2FsReadDirectoryParams,
  "fs/remove": CodexSchema.V2FsRemoveParams,
  "fs/copy": CodexSchema.V2FsCopyParams,
  "fs/watch": CodexSchema.V2FsWatchParams,
  "fs/unwatch": CodexSchema.V2FsUnwatchParams,
  "skills/config/write": CodexSchema.V2SkillsConfigWriteParams,
  "plugin/install": CodexSchema.V2PluginInstallParams,
  "plugin/uninstall": CodexSchema.V2PluginUninstallParams,
  "turn/start": CodexSchema.V2TurnStartParams,
  "turn/steer": CodexSchema.V2TurnSteerParams,
  "turn/interrupt": CodexSchema.V2TurnInterruptParams,
  "review/start": CodexSchema.V2ReviewStartParams,
  "model/list": CodexSchema.V2ModelListParams,
  "experimentalFeature/list": CodexSchema.V2ExperimentalFeatureListParams,
  "experimentalFeature/enablement/set": CodexSchema.V2ExperimentalFeatureEnablementSetParams,
  "mcpServer/oauth/login": CodexSchema.V2McpServerOauthLoginParams,
  "config/mcpServer/reload": undefined,
  "mcpServerStatus/list": CodexSchema.V2ListMcpServerStatusParams,
  "mcpServer/resource/read": CodexSchema.V2McpResourceReadParams,
  "mcpServer/tool/call": CodexSchema.V2McpServerToolCallParams,
  "windowsSandbox/setupStart": CodexSchema.V2WindowsSandboxSetupStartParams,
  "account/login/start": CodexSchema.V2LoginAccountParams,
  "account/login/cancel": CodexSchema.V2CancelLoginAccountParams,
  "account/logout": undefined,
  "account/rateLimits/read": undefined,
  "account/sendAddCreditsNudgeEmail": CodexSchema.V2SendAddCreditsNudgeEmailParams,
  "feedback/upload": CodexSchema.V2FeedbackUploadParams,
  "command/exec": CodexSchema.V2CommandExecParams,
  "command/exec/write": CodexSchema.V2CommandExecWriteParams,
  "command/exec/terminate": CodexSchema.V2CommandExecTerminateParams,
  "command/exec/resize": CodexSchema.V2CommandExecResizeParams,
  "config/read": CodexSchema.V2ConfigReadParams,
  "externalAgentConfig/detect": CodexSchema.V2ExternalAgentConfigDetectParams,
  "externalAgentConfig/import": CodexSchema.V2ExternalAgentConfigImportParams,
  "config/value/write": CodexSchema.V2ConfigValueWriteParams,
  "config/batchWrite": CodexSchema.V2ConfigBatchWriteParams,
  "configRequirements/read": undefined,
  "account/read": CodexSchema.V2GetAccountParams,
  getConversationSummary: CodexSchema.GetConversationSummaryParams,
  gitDiffToRemote: CodexSchema.GitDiffToRemoteParams,
  getAuthStatus: CodexSchema.GetAuthStatusParams,
  fuzzyFileSearch: CodexSchema.FuzzyFileSearchParams,
} as const;

export const CLIENT_REQUEST_RESPONSES = {
  initialize: CodexSchema.V1InitializeResponse,
  "thread/start": CodexSchema.V2ThreadStartResponse,
  "thread/resume": CodexSchema.V2ThreadResumeResponse,
  "thread/fork": CodexSchema.V2ThreadForkResponse,
  "thread/archive": CodexSchema.V2ThreadArchiveResponse,
  "thread/unsubscribe": CodexSchema.V2ThreadUnsubscribeResponse,
  "thread/name/set": CodexSchema.V2ThreadSetNameResponse,
  "thread/metadata/update": CodexSchema.V2ThreadMetadataUpdateResponse,
  "thread/unarchive": CodexSchema.V2ThreadUnarchiveResponse,
  "thread/compact/start": CodexSchema.V2ThreadCompactStartResponse,
  "thread/shellCommand": CodexSchema.V2ThreadShellCommandResponse,
  "thread/rollback": CodexSchema.V2ThreadRollbackResponse,
  "thread/list": CodexSchema.V2ThreadListResponse,
  "thread/loaded/list": CodexSchema.V2ThreadLoadedListResponse,
  "thread/read": CodexSchema.V2ThreadReadResponse,
  "thread/turns/list": CodexSchema.V2ThreadTurnsListResponse,
  "thread/inject_items": CodexSchema.V2ThreadInjectItemsResponse,
  "skills/list": CodexSchema.V2SkillsListResponse,
  "marketplace/add": CodexSchema.V2MarketplaceAddResponse,
  "marketplace/remove": CodexSchema.V2MarketplaceRemoveResponse,
  "plugin/list": CodexSchema.V2PluginListResponse,
  "plugin/read": CodexSchema.V2PluginReadResponse,
  "app/list": CodexSchema.V2AppsListResponse,
  "device/key/create": CodexSchema.V2DeviceKeyCreateResponse,
  "device/key/public": CodexSchema.V2DeviceKeyPublicResponse,
  "device/key/sign": CodexSchema.V2DeviceKeySignResponse,
  "fs/readFile": CodexSchema.V2FsReadFileResponse,
  "fs/writeFile": CodexSchema.V2FsWriteFileResponse,
  "fs/createDirectory": CodexSchema.V2FsCreateDirectoryResponse,
  "fs/getMetadata": CodexSchema.V2FsGetMetadataResponse,
  "fs/readDirectory": CodexSchema.V2FsReadDirectoryResponse,
  "fs/remove": CodexSchema.V2FsRemoveResponse,
  "fs/copy": CodexSchema.V2FsCopyResponse,
  "fs/watch": CodexSchema.V2FsWatchResponse,
  "fs/unwatch": CodexSchema.V2FsUnwatchResponse,
  "skills/config/write": CodexSchema.V2SkillsConfigWriteResponse,
  "plugin/install": CodexSchema.V2PluginInstallResponse,
  "plugin/uninstall": CodexSchema.V2PluginUninstallResponse,
  "turn/start": CodexSchema.V2TurnStartResponse,
  "turn/steer": CodexSchema.V2TurnSteerResponse,
  "turn/interrupt": CodexSchema.V2TurnInterruptResponse,
  "review/start": CodexSchema.V2ReviewStartResponse,
  "model/list": CodexSchema.V2ModelListResponse,
  "experimentalFeature/list": CodexSchema.V2ExperimentalFeatureListResponse,
  "experimentalFeature/enablement/set": CodexSchema.V2ExperimentalFeatureEnablementSetResponse,
  "mcpServer/oauth/login": CodexSchema.V2McpServerOauthLoginResponse,
  "config/mcpServer/reload": CodexSchema.V2McpServerRefreshResponse,
  "mcpServerStatus/list": CodexSchema.V2ListMcpServerStatusResponse,
  "mcpServer/resource/read": CodexSchema.V2McpResourceReadResponse,
  "mcpServer/tool/call": CodexSchema.V2McpServerToolCallResponse,
  "windowsSandbox/setupStart": CodexSchema.V2WindowsSandboxSetupStartResponse,
  "account/login/start": CodexSchema.V2LoginAccountResponse,
  "account/login/cancel": CodexSchema.V2CancelLoginAccountResponse,
  "account/logout": CodexSchema.V2LogoutAccountResponse,
  "account/rateLimits/read": CodexSchema.V2GetAccountRateLimitsResponse,
  "account/sendAddCreditsNudgeEmail": CodexSchema.V2SendAddCreditsNudgeEmailResponse,
  "feedback/upload": CodexSchema.V2FeedbackUploadResponse,
  "command/exec": CodexSchema.V2CommandExecResponse,
  "command/exec/write": CodexSchema.V2CommandExecWriteResponse,
  "command/exec/terminate": CodexSchema.V2CommandExecTerminateResponse,
  "command/exec/resize": CodexSchema.V2CommandExecResizeResponse,
  "config/read": CodexSchema.V2ConfigReadResponse,
  "externalAgentConfig/detect": CodexSchema.V2ExternalAgentConfigDetectResponse,
  "externalAgentConfig/import": CodexSchema.V2ExternalAgentConfigImportResponse,
  "config/value/write": CodexSchema.V2ConfigWriteResponse,
  "config/batchWrite": CodexSchema.V2ConfigWriteResponse,
  "configRequirements/read": CodexSchema.V2ConfigRequirementsReadResponse,
  "account/read": CodexSchema.V2GetAccountResponse,
  getConversationSummary: CodexSchema.GetConversationSummaryResponse,
  gitDiffToRemote: CodexSchema.GitDiffToRemoteResponse,
  getAuthStatus: CodexSchema.GetAuthStatusResponse,
  fuzzyFileSearch: CodexSchema.FuzzyFileSearchResponse,
} as const;

export const CLIENT_NOTIFICATION_PARAMS = {
  initialized: undefined,
} as const;

export const SERVER_REQUEST_PARAMS = {
  "item/commandExecution/requestApproval": CodexSchema.CommandExecutionRequestApprovalParams,
  "item/fileChange/requestApproval": CodexSchema.FileChangeRequestApprovalParams,
  "item/tool/requestUserInput": CodexSchema.ToolRequestUserInputParams,
  "mcpServer/elicitation/request": CodexSchema.McpServerElicitationRequestParams,
  "item/permissions/requestApproval": CodexSchema.PermissionsRequestApprovalParams,
  "item/tool/call": CodexSchema.DynamicToolCallParams,
  "account/chatgptAuthTokens/refresh": CodexSchema.ChatgptAuthTokensRefreshParams,
  applyPatchApproval: CodexSchema.ApplyPatchApprovalParams,
  execCommandApproval: CodexSchema.ExecCommandApprovalParams,
} as const;

export const SERVER_REQUEST_RESPONSES = {
  "item/commandExecution/requestApproval": CodexSchema.CommandExecutionRequestApprovalResponse,
  "item/fileChange/requestApproval": CodexSchema.FileChangeRequestApprovalResponse,
  "item/tool/requestUserInput": CodexSchema.ToolRequestUserInputResponse,
  "mcpServer/elicitation/request": CodexSchema.McpServerElicitationRequestResponse,
  "item/permissions/requestApproval": CodexSchema.PermissionsRequestApprovalResponse,
  "item/tool/call": CodexSchema.DynamicToolCallResponse,
  "account/chatgptAuthTokens/refresh": CodexSchema.ChatgptAuthTokensRefreshResponse,
  applyPatchApproval: CodexSchema.ApplyPatchApprovalResponse,
  execCommandApproval: CodexSchema.ExecCommandApprovalResponse,
} as const;

export const SERVER_NOTIFICATION_PARAMS = {
  error: CodexSchema.V2ErrorNotification,
  "thread/started": CodexSchema.V2ThreadStartedNotification,
  "thread/status/changed": CodexSchema.V2ThreadStatusChangedNotification,
  "thread/archived": CodexSchema.V2ThreadArchivedNotification,
  "thread/unarchived": CodexSchema.V2ThreadUnarchivedNotification,
  "thread/closed": CodexSchema.V2ThreadClosedNotification,
  "skills/changed": CodexSchema.V2SkillsChangedNotification,
  "thread/name/updated": CodexSchema.V2ThreadNameUpdatedNotification,
  "thread/tokenUsage/updated": CodexSchema.V2ThreadTokenUsageUpdatedNotification,
  "turn/started": CodexSchema.V2TurnStartedNotification,
  "hook/started": CodexSchema.V2HookStartedNotification,
  "turn/completed": CodexSchema.V2TurnCompletedNotification,
  "hook/completed": CodexSchema.V2HookCompletedNotification,
  "turn/diff/updated": CodexSchema.V2TurnDiffUpdatedNotification,
  "turn/plan/updated": CodexSchema.V2TurnPlanUpdatedNotification,
  "item/started": CodexSchema.V2ItemStartedNotification,
  "item/autoApprovalReview/started": CodexSchema.V2ItemGuardianApprovalReviewStartedNotification,
  "item/autoApprovalReview/completed":
    CodexSchema.V2ItemGuardianApprovalReviewCompletedNotification,
  "item/completed": CodexSchema.V2ItemCompletedNotification,
  "rawResponseItem/completed": CodexSchema.V2RawResponseItemCompletedNotification,
  "item/agentMessage/delta": CodexSchema.V2AgentMessageDeltaNotification,
  "item/plan/delta": CodexSchema.V2PlanDeltaNotification,
  "command/exec/outputDelta": CodexSchema.V2CommandExecOutputDeltaNotification,
  "item/commandExecution/outputDelta": CodexSchema.V2CommandExecutionOutputDeltaNotification,
  "item/commandExecution/terminalInteraction": CodexSchema.V2TerminalInteractionNotification,
  "item/fileChange/outputDelta": CodexSchema.V2FileChangeOutputDeltaNotification,
  "item/fileChange/patchUpdated": CodexSchema.V2FileChangePatchUpdatedNotification,
  "serverRequest/resolved": CodexSchema.V2ServerRequestResolvedNotification,
  "item/mcpToolCall/progress": CodexSchema.V2McpToolCallProgressNotification,
  "mcpServer/oauthLogin/completed": CodexSchema.V2McpServerOauthLoginCompletedNotification,
  "mcpServer/startupStatus/updated": CodexSchema.V2McpServerStatusUpdatedNotification,
  "account/updated": CodexSchema.V2AccountUpdatedNotification,
  "account/rateLimits/updated": CodexSchema.V2AccountRateLimitsUpdatedNotification,
  "app/list/updated": CodexSchema.V2AppListUpdatedNotification,
  "externalAgentConfig/import/completed":
    CodexSchema.V2ExternalAgentConfigImportCompletedNotification,
  "fs/changed": CodexSchema.V2FsChangedNotification,
  "item/reasoning/summaryTextDelta": CodexSchema.V2ReasoningSummaryTextDeltaNotification,
  "item/reasoning/summaryPartAdded": CodexSchema.V2ReasoningSummaryPartAddedNotification,
  "item/reasoning/textDelta": CodexSchema.V2ReasoningTextDeltaNotification,
  "thread/compacted": CodexSchema.V2ContextCompactedNotification,
  "model/rerouted": CodexSchema.V2ModelReroutedNotification,
  warning: CodexSchema.V2WarningNotification,
  deprecationNotice: CodexSchema.V2DeprecationNoticeNotification,
  configWarning: CodexSchema.V2ConfigWarningNotification,
  "fuzzyFileSearch/sessionUpdated": CodexSchema.FuzzyFileSearchSessionUpdatedNotification,
  "fuzzyFileSearch/sessionCompleted": CodexSchema.FuzzyFileSearchSessionCompletedNotification,
  "thread/realtime/started": CodexSchema.V2ThreadRealtimeStartedNotification,
  "thread/realtime/itemAdded": CodexSchema.V2ThreadRealtimeItemAddedNotification,
  "thread/realtime/transcript/delta": CodexSchema.V2ThreadRealtimeTranscriptDeltaNotification,
  "thread/realtime/transcript/done": CodexSchema.V2ThreadRealtimeTranscriptDoneNotification,
  "thread/realtime/outputAudio/delta": CodexSchema.V2ThreadRealtimeOutputAudioDeltaNotification,
  "thread/realtime/sdp": CodexSchema.V2ThreadRealtimeSdpNotification,
  "thread/realtime/error": CodexSchema.V2ThreadRealtimeErrorNotification,
  "thread/realtime/closed": CodexSchema.V2ThreadRealtimeClosedNotification,
  "windows/worldWritableWarning": CodexSchema.V2WindowsWorldWritableWarningNotification,
  "windowsSandbox/setupCompleted": CodexSchema.V2WindowsSandboxSetupCompletedNotification,
  "account/login/completed": CodexSchema.V2AccountLoginCompletedNotification,
} as const;
